### ISSUE TITLE
Problem with mutation: Expected type "Date" but returns error "Unknown type"

### ISSUE THREAD

**Issue by proehlen** [tjmehta/graphql-date#6]
I have an input type defined like this:
```
  # Exchange rate fields that can be set by the client on update
  input ExchangeRateUpdate {
    date: GraphQLDate
    currency_id: Int
    rate: Float
  }
```
In the automatically generated iGraphQL documentation it shows the type being "Date" not "GraphlQLDate":
![image](https://cloud.githubusercontent.com/assets/8384068/23014532/fc50c860-f461-11e6-8329-aa4b68105a45.png)

If I define my mutation with type "Date" as this:
```
mutation ($id: Int!, $date: Date) {
  updateExchangeRate(id: $id, input: {date: $date}) {
    id
    date
    rate
  }
}
```
I get the following error back:
```
{
  "errors": [
    {
      "message": "Unknown type \"Date\".",
      "locations": [
        {
          "line": 1,
          "column": 29
        }
      ]
    }
  ]
}
```
If I define my mutation with type "GraphQLDate", the editor reports an error (see tooltip) but the query works:

![image](https://cloud.githubusercontent.com/assets/8384068/23014730/bc0ad826-f462-11e6-867a-5d8ba85b02a9.png)

**Comment by tjmehta** [comment]
Hey Peter,

I am currently traveling but should be able to get a look today. Any ideas?
Maybe try out another custom type in npm and see how they work? Happy to
accept a PR while on the go

Lmk

**Comment by proehlen** [comment]
Hi Tejesh,. Thanks for the quick response.  I don't think it's urgent since it only affects iGraphQL.  It's just misleading.  Could even be a bug in iGraphQL itself.

I'll be able to take a look whether other custom type packages can shed some light on it in the next day or so.

Cheers

**Comment by tjmehta** [comment]
Gotcha, at a glance I thought it was broken for mutations period

**Comment by proehlen** [comment]
Hi Tejesh, 

I've looked into this and found that if I rename all of my type declarations to `Date` instead of `GraphQLDate` that the problem goes away.  E.g.:

```
export const schema = `
  
  # A registered application user.  Includes anyone with a user id and
  # password to log in to the system
  type User {
    id: Int!
    last_login: Date!
    ...
```

I suspect is might be because of this line from `index.js` in your project:
```
module.exports = new GraphQLScalarType({
  name: 'Date',
  ...
```

Perhaps it should be `name: 'GraphQLDate',`?

In any case, closing this since the problem can be fixed on my end.

Thanks
