### ISSUE TITLE
Error: date field type must be Output Type but got: undefined.

### ISSUE THREAD

**Issue by xzegga** [tjmehta/graphql-date#8]
I have a graphql server running with node/expres and ES6, I am trying to migrate to typescript, in graphql schema I have experiencing some problems with date types. I know that graphql does not contain a native date type, but in my ES6 implementation, I have used graphql-date to suply this limitation.

```
import {
    GraphQLObjectType,
    GraphQLSchema,
    GraphQLID,
} from 'graphql';

import GraphQLDate from 'graphql-date';

const events = new GraphQLObjectType({
    name: 'events',
    description: 'This represent an Event',
    fields: () => {
        return {
            id: {
                type: GraphQLID,
                resolve(event) {
                    return event.id;
                }
            },
            start: {
                type: GraphQLDate,
                resolve(event) {
                    return event.start;
                }
            }
        };
    }
});
```

the problem is that in my project with typescript when run server I get this message:

`Error: events.start field type must be Output Type but got: undefined.`

**Comment by tjmehta** [comment]
Out of curiosity, what happens when you rename the var `Date`?

**Comment by tjmehta** [comment]
Is `event.start` `undefined`?

**Comment by xzegga** [comment]
yes, events.start, it's seen that the problem is caused by GraphQLDate, If I change for string foro example not get this error.

**Comment by xzegga** [comment]
Yes, the problem is caused by GraphQLDate, if I log to console GraphQLDate and return undefined. :( what's the problem here.

**Comment by xzegga** [comment]
I got the error!, the problem is that graphql-date not return any default value. my solution was: 

`import* as GraphQLDate from 'graphql-date';`

**Comment by xzegga** [comment]
I got the error!, the problem is that graphql-date not return any default value. my solution was:

import * as GraphQLDate from 'graphql-date';
